/*
 * driver_config.h
 *
 *  Created on: Aug 31, 2010
 *      Author: nxp28548
 */

#ifndef DRIVER_CONFIG_H_
#define DRIVER_CONFIG_H

#if defined(lpc11c14)
#include <cmsis/LPC11xx.h>
#endif

#if defined(lpc1768)
#include <cmsis/LPC17xx.h>
#endif

#undef CAN_UART_DEBUG

#define CONFIG_ENABLE_DRIVER_CRP						1
#define CONFIG_CRP_SETTING_NO_CRP						1

#define CONFIG_ENABLE_DRIVER_TIMER32					1
#define CONFIG_TIMER32_DEFAULT_TIMER32_0_IRQHANDLER		1

#define CONFIG_ENABLE_DRIVER_GPIO						1

#define CONFIG_ENABLE_DRIVER_UART						1
#define CONFIG_UART_DEFAULT_UART_IRQHANDLER				1
#define CONFIG_UART_ENABLE_INTERRUPT					1

#define CONFIG_ENABLE_DRIVER_CAN						1
#define CONFIG_CAN_DEFAULT_CAN_IRQHANDLER				1

//Define Test Mode to print debugging messages. When undefined, the messages are
//removed by pre-processor 
//#define DEBUG_MODE                                    1

//I2C
#define CONFIG_ENABLE_DRIVER_I2C						1
#define CONFIG_I2C_DEFAULT_I2C_IRQHANDLER				1

/** Parameter source addresses and channels **/
#define SCANDAL_IN_CHANNEL_SPEED1_ADDRESS 61
#define SCANDAL_IN_CHANNEL_SPEED1_CHANNEL 0

#define SCANDAL_IN_CHANNEL_SPEED2_ADDRESS 1
#define SCANDAL_IN_CHANNEL_SPEED2_CHANNEL 34

#define SCANDAL_IN_CHANNEL_BV1_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_BV1_CHANNEL 2

#define SCANDAL_IN_CHANNEL_BV2_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_BV2_CHANNEL 3

#define SCANDAL_IN_CHANNEL_CC1_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_CC1_CHANNEL 4

#define SCANDAL_IN_CHANNEL_CC2_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_CC2_CHANNEL 5

#define SCANDAL_IN_CHANNEL_PCH1_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_PCH1_CHANNEL 6

#define SCANDAL_IN_CHANNEL_PCH2_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_PCH2_CHANNEL 7

#define SCANDAL_IN_CHANNEL_MCT_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_MCT_CHANNEL 8

#define SCANDAL_IN_CHANNEL_MV_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_MV_CHANNEL 25

#define SCANDAL_IN_CHANNEL_MI_ADDRESS 1 
#define SCANDAL_IN_CHANNEL_MI_CHANNEL 34

#define SCANDAL_IN_CHANNEL_BI_ADDRESS 61 
#define SCANDAL_IN_CHANNEL_BI_CHANNEL 2

#define SCANDAL_ADDRESS_OVERRIDE_ENABLE 1
#define SCANDAL_ADDRESS_OVERRIDE 1

/** Parameter source addresses and channels **/
#define SCANDAL_IN_CHANNEL_0_OVERRIDE_ENABLE    1  
#define SCANDAL_IN_CHANNEL_0_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_SPEED1_ADDRESS 
#define SCANDAL_IN_CHANNEL_0_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_SPEED1_CHANNEL

#define SCANDAL_IN_CHANNEL_1_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_1_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_SPEED2_ADDRESS
#define SCANDAL_IN_CHANNEL_1_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_SPEED2_CHANNEL

#define SCANDAL_IN_CHANNEL_2_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_2_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_BV1_ADDRESS
#define SCANDAL_IN_CHANNEL_2_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_BV1_CHANNEL

#define SCANDAL_IN_CHANNEL_3_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_3_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_BV2_ADDRESS
#define SCANDAL_IN_CHANNEL_3_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_BV2_CHANNEL

#define SCANDAL_IN_CHANNEL_4_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_4_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_CC1_ADDRESS
#define SCANDAL_IN_CHANNEL_4_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_CC1_CHANNEL

#define SCANDAL_IN_CHANNEL_5_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_5_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_CC1_ADDRESS
#define SCANDAL_IN_CHANNEL_5_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_CC2_CHANNEL

#define SCANDAL_IN_CHANNEL_6_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_6_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_PCH1_ADDRESS
#define SCANDAL_IN_CHANNEL_6_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_PCH1_CHANNEL

#define SCANDAL_IN_CHANNEL_7_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_7_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_PCH2_ADDRESS
#define SCANDAL_IN_CHANNEL_7_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_PCH2_CHANNEL

#define SCANDAL_IN_CHANNEL_8_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_8_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_MCT_ADDRESS 
#define SCANDAL_IN_CHANNEL_8_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_MCT_CHANNEL 

#define SCANDAL_IN_CHANNEL_9_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_9_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_MV_ADDRESS 
#define SCANDAL_IN_CHANNEL_9_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_MV_CHANNEL 

#define SCANDAL_IN_CHANNEL_10_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_10_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_MI_ADDRESS
#define SCANDAL_IN_CHANNEL_10_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_MI_CHANNEL

#define SCANDAL_IN_CHANNEL_11_OVERRIDE_ENABLE    1
#define SCANDAL_IN_CHANNEL_11_OVERRIDE_ADDRESS SCANDAL_IN_CHANNEL_BI_ADDRESS
#define SCANDAL_IN_CHANNEL_11_OVERRIDE_CHANNEL SCANDAL_IN_CHANNEL_BI_CHANNEL

/* DRIVER_CONFIG_H_ */
#endif

